---
title: "FCMData_clustering"
author: "JiangXinYu0313"
date: "2023-09-29"
output: html_document
---

## Read Data

```{r eval=FALSE, include=FALSE}
merge_rawData <- read.csv("/database/jiangxinyu/Project/FCM_Project/data/merge_rawData.csv")
head(merge_rawData)
dim(merge_rawData)
names(merge_rawData)
```

## Data Clean subset
```{r eval=FALSE, include=FALSE}
merge_rawData_clean <- merge_rawData[,c(seq(11,67,3),72)]
merge_rawData_clean <- merge_rawData_clean[,-15]#去掉LIVE
merge_rawData_clean_subset <- merge_rawData_clean[sample(1000000),]
```

```{r echo=TRUE}
library(openxlsx)
library(tidyr)
library(dplyr)
library(ggplot2)
library(ggbiplot)
library(Seurat)
library(SeuratObject)
library(factoextra)
library(FactoMineR)
library(ggpubr)
library(workflowr)
library(clustree)
library(lightHippo)
library(future)
library(RColorBrewer)
```

## Seurat clustering 
### Compute
```{r eval=FALSE, include=FALSE}
plan("multicore", workers = 8)
#解除运行内存限制
options(future.globals.maxSize = 100000 * 1024^5)

set.seed(1)
featurename <- c("CD4","GZMB","ICOS","CD45RA","IL-21","IL-4","TNF-alpha","IL-17","PD-1","CD3","CD183","CCR6","CD185","CCR7","CD69","IFN-Gamma","CD8","IL-2","index")
names(merge_rawData_clean_subset) <- featurename
#创建Seurat时虽已生成data但未标准化 data=counts
FCMData.SeuratObj <- CreateSeuratObject(counts = t(merge_rawData_clean_subset[,c(1:(length(featurename)-1))]),assay = "FCMData_subset",project = "FCMData")
FCMData.SeuratObj@meta.data[["index_FCMData_subset"]] <- merge_rawData_clean_subset[,length(featurename)]

FCMData.SeuratObj <- NormalizeData(FCMData.SeuratObj,normalization.method = "CLR")

FCMData.SeuratObj <- FindVariableFeatures(FCMData.SeuratObj)

# Scaling RNA data, we only scale the variable features here for efficiency
FCMData.SeuratObj <- ScaleData(FCMData.SeuratObj, features = VariableFeatures(FCMData.SeuratObj))
# Run PCA
FCMData.SeuratObj <- RunPCA(FCMData.SeuratObj,features = VariableFeatures(FCMData.SeuratObj),)
ElbowPlot(FCMData.SeuratObj)
dim <- dim(FCMData.SeuratObj@reductions[["pca"]])[2]-5

FCMData.SeuratObj <- FindNeighbors(FCMData.SeuratObj, reduction = "pca", dims = 1:dim)

FCMData.SeuratObj <- FindClusters(FCMData.SeuratObj, resolution = c(seq(0.5,0.9,0.1)), verbose = FALSE)#一小时左右 plan函数并行处理

FCMData.SeuratObj <- RunUMAP(FCMData.SeuratObj,dims = 1:dim)
FCMData.SeuratObj <- RunTSNE(FCMData.SeuratObj,dims = 1:dim)

saveRDS(FCMData.SeuratObj,"/database/jiangxinyu/Project/FCM_Project/data/FCMData.SeuratObj.rds")
```

### Visualization
```{r echo=TRUE}
FCMData.SeuratObj <- readRDS("/database/jiangxinyu/Project/FCM_Project/data/FCMData.SeuratObj.rds")
# clustree(FCMData.SeuratObj, prefix = "FCMData_subset_snn_res.",node_text_size=4)
DimPlot(FCMData.SeuratObj,reduction = "umap",raster=TRUE,group.by = "index_FCMData_subset")+ggtitle("FCMData_index.UMAP")+
  theme(plot.title = element_text(size = 12,hjust = 0.5))

DimPlot(FCMData.SeuratObj,reduction = "umap",raster=TRUE)+ggtitle("FCMData.UMAP")+
  theme(plot.title = element_text(size = 12,hjust = 0.5))
DimPlot(FCMData.SeuratObj,reduction = "tsne",raster=TRUE)+ggtitle("FCMData.TSNE")+
  theme(plot.title = element_text(size = 12,hjust = 0.5))

FeaturePlot(FCMData.SeuratObj,reduction = "umap",features = c("CD3"),raster = F,slot = "scale.data")
FeaturePlot(FCMData.SeuratObj,reduction = "umap",features = c("CD4"),raster = F,slot = "scale.data")
FeaturePlot(FCMData.SeuratObj,reduction = "umap",features = c("CD8"),raster = F,slot = "scale.data")
```


```{r echo=TRUE}

size <- 10
Features <- FCMData.SeuratObj@assays[["FCMData_subset"]]@var.features
DotPlot(FCMData.SeuratObj, features = Features,scale = T)+
  coord_flip()+
  theme_set(theme_bw(base_size = size,base_family = "serif"))+
  scale_color_gradientn(colours = c( "#FFFFF0","#FFEDA0","#FD8D3C","#FC4E2A","#800026"))+
  labs(title = "FCMData_subset_snn_res.0.9")+
  theme(axis.text = element_text(family = "serif", #字体
                                  color = "black",      #字体颜色
                                  size = size,          #字体大小
                                  hjust = 0.5,          #字体左右的位置
                                  vjust = 0.5,          #字体上下的高度
                                  angle = 0),panel.grid=element_blank(),plot.title = element_text(size = size+2,hjust = 0.5))
print(table(FCMData.SeuratObj@meta.data[["FCMData_subset_snn_res.0.9"]]))
DotPlot(FCMData.SeuratObj, features = Features,scale = T,group.by = "FCMData_subset_snn_res.0.5")+
  coord_flip()+
  theme_set(theme_bw(base_size = size,base_family = "serif"))+
  scale_color_gradientn(colours = c( "#FFFFFF","#FFFFC0","blue","#800026"))+
  labs(title = "FCMData_subset_snn_res.0.5")+
  theme(axis.text = element_text(family = "serif", #字体
                                  color = "black",      #字体颜色
                                  size = size,          #字体大小
                                  hjust = 0.5,          #字体左右的位置
                                  vjust = 0.5,          #字体上下的高度
                                  angle = 0),panel.grid=element_blank(),plot.title = element_text(size = size+2,hjust = 0.5))

DotPlot(FCMData.SeuratObj, features = Features,scale = T,group.by = "FCMData_subset_snn_res.0.5",idents = c(seq(0,20)))+
  coord_flip()+
  theme_set(theme_bw(base_size = size,base_family = "serif"))+
  scale_color_gradientn(colours = c( "#FFFFFF","#FFFFC0","blue","#800026"))+
  labs(title = "FCMData_subset_snn_res.0.5")+
  theme(axis.text = element_text(family = "serif", #字体
                                  color = "black",      #字体颜色
                                  size = size,          #字体大小
                                  hjust = 0.5,          #字体左右的位置
                                  vjust = 0.5,          #字体上下的高度
                                  angle = 0),panel.grid=element_blank(),plot.title = element_text(size = size+2,hjust = 0.5))
DotPlot(FCMData.SeuratObj, features = Features,scale = T,group.by = "FCMData_subset_snn_res.0.5",idents = c(seq(0,20)))+
  coord_flip()+
  theme_set(theme_bw(base_size = size,base_family = "serif"))+
  scale_color_gradientn(colours = c( "#FFFFF0","#FFEDA0","#FD8D3C","#FC4E2A","#800026"))+
  labs(title = "FCMData_subset_snn_res.0.5")+
  theme(axis.text = element_text(family = "serif", #字体
                                  color = "black",      #字体颜色
                                  size = size,          #字体大小
                                  hjust = 0.5,          #字体左右的位置
                                  vjust = 0.5,          #字体上下的高度
                                  angle = 0),panel.grid=element_blank(),plot.title = element_text(size = size+2,hjust = 0.5))
print(table(FCMData.SeuratObj@meta.data[["FCMData_subset_snn_res.0.5"]]))
```


## lightHippo clustering(debug)
```{r eval=FALSE, include=FALSE}
library(lightHippo)

dat <- as.matrix(t(merge_rawData_clean_subset[,c(1:(length(featurename)-1))]))
merge_rawData_clean_subset.lightHippo <- lightHIPPO(dat, K.round = 29,random.num = 18)   
```


```{r eval=FALSE, include=FALSE}
library(SingleCellExperiment)
sce = DuoClustering2018::sce_full_Zhengmix4eq(metadata = FALSE)
head(sce)
dat <- SingleCellExperiment::counts(sce)
check_ttt <- lightHIPPO(dat, K.round = 9, initial.round = 0)   
```


```{r eval=FALSE, include=FALSE}
lightHIPPO <- function(dat, K.round = 10, initial.labels = NULL, initial.round = 0, stop_at = 500, correctByK = FALSE, override.Zscore.cutoff = NULL, smallest.cluster.num = 200, random.num = 2500, move.by.inflation = TRUE)

  
  
dat
K.round = 10
initial.labels = NULL
initial.round = 0
stop_at = 500
correctByK = FALSE
override.Zscore.cutoff = NULL
smallest.cluster.num = 200
random.num = 10
move.by.inflation = TRUE



  require(irlba)
  total.num.cell <- ncol(dat)
  total.num.gene <- nrow(dat)

  if(!is.null(initial.labels)){
    if(length(initial.labels) != total.num.cell){
      stop("Length of initial group labels doesn't match the number of cell.")
    }
    initial.round <- 0
  }

  if(!is.null(override.Zscore.cutoff)) {
    Zscore.cutoff <- override.Zscore.cutoff
  } else if(correctByK == FALSE){
    Zscore.cutoff <- cut_off_zscore(total.num.gene)
  } else {
    Zscore.cutoff <- cut_off_zscore(total.num.gene*K)
  }

  if(move.by.inflation == TRUE){

    ### calculate the inflation number for each cluster based on a random set of genes ###
    set.seed(1234567)
    randomIDs <- sample(1:total.num.gene, random.num)

    if(is.null(initial.labels) & initial.round > 0) {

      initial_clusters <- initialize_HIPPO(dat, initial.round = initial.round, stop_at = stop_at, Zscore.cutoff = Zscore.cutoff)
      next_round_IDs <- initial_clusters$next_round_IDs
      res <- initial_clusters

      selected.gene.list <- NULL
      selected.gene.Zscore <- NULL
      inflation.tracking <- NULL
      for(i in 1:c(initial.round+1)){
        inflation.tracking <- c(inflation.tracking, check_zero_inflation_numbers(dat[randomIDs, next_round_IDs%in%i], Zscore.cutoff = Zscore.cutoff))
      }
      names(inflation.tracking) <- 1:c(initial.round + 1)

      for(i.round in (initial.round + 1):K.round){

        go_with_higher_inflationID <- selectCluster_to_proceed_inflation(inflation.tracking, next_round_IDs, cluster.size.cutoff = smallest.cluster.num)
        selected.dat <- dat[, next_round_IDs%in%go_with_higher_inflationID]
        selected.res <- select_features_full(selected.dat, Zscore.cutoff = Zscore.cutoff)
        selected.ID <- selected.res$selected
        selected.Zscore <- selected.res$Zscore

        new.subset.dat <- selected.dat[selected.ID, ]
        clusterID <- run_kmeans_clustering(new.subset.dat)
        next_round_IDs[next_round_IDs%in%go_with_higher_inflationID][clusterID == 2] <- i.round + 1
        res$sequence <- c(res$sequence, go_with_higher_inflationID)

        inflation.tracking[go_with_higher_inflationID] <- check_zero_inflation_numbers(dat[randomIDs, next_round_IDs%in%go_with_higher_inflationID], Zscore.cutoff = Zscore.cutoff)
        inflation.tracking <- c(inflation.tracking, check_zero_inflation_numbers(dat[randomIDs, next_round_IDs%in%(i.round+1)], Zscore.cutoff = Zscore.cutoff))
        names(inflation.tracking)[i.round+1] <- i.round+1

        selected.gene.list[[i.round]] <- selected.ID
        selected.gene.Zscore[[i.round]] <- selected.Zscore
      }
      res$next_round_IDs <- next_round_IDs
      names(res$sequence) <- 1:length(res$sequence)+2
      res$selected.gene.list <- selected.gene.list
      res$selected.gene.Zscore <- selected.gene.Zscore
      res$type <- "Rooted"
      res$initial.clusters <- NULL

    } else if(is.null(initial.labels) & initial.round == 0) {

      res <- NULL
      res$sequence <- NULL
      inflation.tracking <- NULL
      selected.gene.list <- NULL
      selected.gene.Zscore <- NULL

      for(i.round in (initial.round + 1):K.round){

        if(i.round == 1){

          selected.res <- select_features_full(dat, Zscore.cutoff = Zscore.cutoff)
          selected.ID <- selected.res$selected
          selected.Zscore <- selected.res$Zscore
          new.subset.dat <- dat[selected.ID, ]
          clusterID <- run_kmeans_clustering(new.subset.dat)
          next_round_IDs <- clusterID
          inflation.tracking[1] <- check_zero_inflation_numbers(dat[randomIDs, next_round_IDs==1], Zscore.cutoff = Zscore.cutoff)
          inflation.tracking[2] <- check_zero_inflation_numbers(dat[randomIDs, next_round_IDs==2], Zscore.cutoff = Zscore.cutoff)
          names(inflation.tracking) <- c(1:2)

          selected.gene.list[[i.round]] <- selected.ID
          selected.gene.Zscore[[i.round]] <- selected.Zscore

        } else {

          go_with_higher_inflationID <- selectCluster_to_proceed_inflation(inflation.tracking, next_round_IDs, cluster.size.cutoff = smallest.cluster.num)
          selected.dat <- dat[, next_round_IDs%in% go_with_higher_inflationID]
          selected.res <- select_features_full(selected.dat, Zscore.cutoff = Zscore.cutoff)
          selected.ID <- selected.res$selected
          selected.Zscore <- selected.res$Zscore

          new.subset.dat <- selected.dat[selected.ID, ]
          clusterID <- run_kmeans_clustering(new.subset.dat)
          next_round_IDs[next_round_IDs%in%go_with_higher_inflationID][clusterID == 2] <- i.round + 1
          res$sequence <- c(res$sequence, go_with_higher_inflationID)

          inflation.tracking[go_with_higher_inflationID] <- check_zero_inflation_numbers(dat[randomIDs, next_round_IDs%in%go_with_higher_inflationID], Zscore.cutoff = Zscore.cutoff)
          inflation.tracking <- c(inflation.tracking, check_zero_inflation_numbers(dat[randomIDs, next_round_IDs%in%(i.round+1)], Zscore.cutoff = Zscore.cutoff))
          names(inflation.tracking)[i.round+1] <- i.round+1

          selected.gene.list[[i.round]] <- selected.ID
          selected.gene.Zscore[[i.round]] <- selected.Zscore
        }

      }
      res$next_round_IDs <- next_round_IDs
      names(res$sequence) <- 1:length(res$sequence)+2
      res$selected.gene.list <- selected.gene.list
      res$selected.gene.Zscore <- selected.gene.Zscore
      res$type <- "Rooted"
      res$initial.clusters <- NULL

    } else if(!is.null(initial.labels)) {

      res <- NULL
      res$sequence <- NULL
      selected.gene.list <- NULL
      selected.gene.Zscore <- NULL

      next_round_IDs <- initial.labels

      inflation.tracking <- NULL
      for(i in 1:max(initial.labels)){
        inflation.tracking <- c(inflation.tracking, check_zero_inflation_numbers(dat[randomIDs, next_round_IDs%in%i], Zscore.cutoff = Zscore.cutoff))
      }
      names(inflation.tracking) <- 1:max(initial.labels)

      for(i.round in (max(initial.labels)):(K.round+max(initial.labels)-1)){

        go_with_higher_inflationID <- selectCluster_to_proceed_inflation(inflation.tracking, next_round_IDs, cluster.size.cutoff = smallest.cluster.num)
        selected.dat <- dat[, next_round_IDs%in% go_with_higher_inflationID]
        selected.res <- select_features_full(selected.dat, Zscore.cutoff = Zscore.cutoff)
        selected.ID <- selected.res$selected
        selected.Zscore <- selected.res$Zscore

        new.subset.dat <- selected.dat[selected.ID, ]
        clusterID <- run_kmeans_clustering(new.subset.dat)
        next_round_IDs[next_round_IDs%in%go_with_higher_inflationID][clusterID == 2] <- i.round + 1
        res$sequence <- c(res$sequence, go_with_higher_inflationID)

        inflation.tracking[go_with_higher_inflationID] <- check_zero_inflation_numbers(dat[randomIDs, next_round_IDs%in%go_with_higher_inflationID], Zscore.cutoff = Zscore.cutoff)
        inflation.tracking <- c(inflation.tracking, check_zero_inflation_numbers(dat[randomIDs, next_round_IDs%in%(i.round+1)], Zscore.cutoff = Zscore.cutoff))
        names(inflation.tracking)[i.round+1] <- i.round+1

        selected.gene.list[[i.round]] <- selected.ID
        selected.gene.Zscore[[i.round]] <- selected.Zscore

      }

      res$next_round_IDs <- next_round_IDs
      names(res$sequence) <- 1:length(res$sequence)+max(initial.labels)
      res$selected.gene.list <- selected.gene.list
      res$selected.gene.Zscore <- selected.gene.Zscore
      res$type <- "Truncated"
      res$initial.clusters <- initial.labels
    }

  }
  
```



```{r echo=TRUE}
sessionInfo()
```

